name: CI

on:
  push:
    paths:
    - 'catalog/*'
    - '!catalog/README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        shopt -s extglob
        echo Add other actions to build,
        echo test, and deploy your project.
        awk -f .github/workflows/toc.awk catalog/!(README).md
