name: Build TOC

on:
  push:
    paths:
    - 'catalog/*'
    - '!catalog/README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build TOC
      run: |
        shopt -s extglob
        awk -f .github/workflows/toc.awk catalog/!(README).md
      shell: bash
