name: Build TOC

on:
  push:
    paths:
    - 'catalog/*'
    - '!catalog/README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build TOC
      run: |
        shopt -s extglob
        awk -f .github/workflows/toc.awk catalog/!(README).md > catalog/README.md
        if ! git diff --no-ext-diff --quiet --exit-code; then
          git add .
          git config --local user.email "${GITHUB_ACTOR}"
          git config --local user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -a -m "update TOC"
          git push -u origin HEAD
        fi
      shell: bash
